test_check_inplace_nn_ELU_xpu_float32 (__main__.TestModuleXPU) ... FAIL
test_check_inplace_nn_ELU_xpu_float64 (__main__.TestModuleXPU) ... ok
test_check_inplace_nn_ReLU_xpu_float32 (__main__.TestModuleXPU) ... FAIL
test_check_inplace_nn_ReLU_xpu_float64 (__main__.TestModuleXPU) ... FAIL
test_factory_kwargs_nn_AvgPool1d_xpu_float32 (__main__.TestModuleXPU) ... ok
test_factory_kwargs_nn_AvgPool1d_xpu_float64 (__main__.TestModuleXPU) ... ok
test_factory_kwargs_nn_ELU_xpu_float32 (__main__.TestModuleXPU) ... ok
test_factory_kwargs_nn_ELU_xpu_float64 (__main__.TestModuleXPU) ... ok
test_factory_kwargs_nn_L1Loss_xpu_float32 (__main__.TestModuleXPU) ... ok
test_factory_kwargs_nn_L1Loss_xpu_float64 (__main__.TestModuleXPU) ... ok
test_factory_kwargs_nn_Linear_xpu_float32 (__main__.TestModuleXPU) ... ok
test_factory_kwargs_nn_Linear_xpu_float64 (__main__.TestModuleXPU) ... ok
test_factory_kwargs_nn_NLLLoss_xpu_float32 (__main__.TestModuleXPU) ... ok
test_factory_kwargs_nn_NLLLoss_xpu_float64 (__main__.TestModuleXPU) ... ok
test_factory_kwargs_nn_ReLU_xpu_float32 (__main__.TestModuleXPU) ... ok
test_factory_kwargs_nn_ReLU_xpu_float64 (__main__.TestModuleXPU) ... ok
test_forward_nn_AvgPool1d_xpu_float32 (__main__.TestModuleXPU) ... FAIL
test_forward_nn_AvgPool1d_xpu_float64 (__main__.TestModuleXPU) ... skipped 'not ready on XPU'
test_forward_nn_ELU_xpu_float32 (__main__.TestModuleXPU) ... ok
test_forward_nn_ELU_xpu_float64 (__main__.TestModuleXPU) ... ok
test_forward_nn_L1Loss_xpu_float32 (__main__.TestModuleXPU) ... ok
test_forward_nn_L1Loss_xpu_float64 (__main__.TestModuleXPU) ... ok
test_forward_nn_Linear_xpu_float32 (__main__.TestModuleXPU) ... FAIL
test_forward_nn_Linear_xpu_float64 (__main__.TestModuleXPU) ... ok
test_forward_nn_NLLLoss_xpu_float32 (__main__.TestModuleXPU) ... ok
test_forward_nn_NLLLoss_xpu_float64 (__main__.TestModuleXPU) ... ok
test_forward_nn_ReLU_xpu_float32 (__main__.TestModuleXPU) ... ok
test_forward_nn_ReLU_xpu_float64 (__main__.TestModuleXPU) ... ok
test_pickle_nn_AvgPool1d_xpu_float32 (__main__.TestModuleXPU) ... ok
test_pickle_nn_AvgPool1d_xpu_float64 (__main__.TestModuleXPU) ... skipped 'not ready on XPU'
test_pickle_nn_ELU_xpu_float32 (__main__.TestModuleXPU) ... ok
test_pickle_nn_ELU_xpu_float64 (__main__.TestModuleXPU) ... ok
test_pickle_nn_L1Loss_xpu_float32 (__main__.TestModuleXPU) ... ok
test_pickle_nn_L1Loss_xpu_float64 (__main__.TestModuleXPU) ... ok
test_pickle_nn_Linear_xpu_float32 (__main__.TestModuleXPU) ... ok
test_pickle_nn_Linear_xpu_float64 (__main__.TestModuleXPU) ... ok
test_pickle_nn_NLLLoss_xpu_float32 (__main__.TestModuleXPU) ... ok
test_pickle_nn_NLLLoss_xpu_float64 (__main__.TestModuleXPU) ... ok
test_pickle_nn_ReLU_xpu_float32 (__main__.TestModuleXPU) ... ok
test_pickle_nn_ReLU_xpu_float64 (__main__.TestModuleXPU) ... ok
test_repr_nn_AvgPool1d_xpu_float32 (__main__.TestModuleXPU) ... ok
test_repr_nn_AvgPool1d_xpu_float64 (__main__.TestModuleXPU) ... ok
test_repr_nn_ELU_xpu_float32 (__main__.TestModuleXPU) ... ok
test_repr_nn_ELU_xpu_float64 (__main__.TestModuleXPU) ... ok
test_repr_nn_L1Loss_xpu_float32 (__main__.TestModuleXPU) ... ok
test_repr_nn_L1Loss_xpu_float64 (__main__.TestModuleXPU) ... ok
test_repr_nn_Linear_xpu_float32 (__main__.TestModuleXPU) ... ok
test_repr_nn_Linear_xpu_float64 (__main__.TestModuleXPU) ... ok
test_repr_nn_NLLLoss_xpu_float32 (__main__.TestModuleXPU) ... ok
test_repr_nn_NLLLoss_xpu_float64 (__main__.TestModuleXPU) ... ok
test_repr_nn_ReLU_xpu_float32 (__main__.TestModuleXPU) ... ok
test_repr_nn_ReLU_xpu_float64 (__main__.TestModuleXPU) ... ok

======================================================================
FAIL: test_check_inplace_nn_ELU_xpu_float32 (__main__.TestModuleXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_modules.py", line 85, in test_wrapper
    return test(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_modules.py", line 202, in test_check_inplace
    self.assertEqual(output_op, output_ip)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1877, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1e-05 and atol=1e-05, found 3 element(s) (out of 3) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 2.162348747253418 (2.162348747253418 vs. 2.3694278276172396e-38), which occurred at index 1.

======================================================================
FAIL: test_check_inplace_nn_ReLU_xpu_float32 (__main__.TestModuleXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_modules.py", line 85, in test_wrapper
    return test(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_modules.py", line 202, in test_check_inplace
    self.assertEqual(output_op, output_ip)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1877, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1e-05 and atol=1e-05, found 66 element(s) (out of 120) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 8.75467300415039 (8.75467300415039 vs. 0.0), which occurred at index (1, 2, 2, 1).

======================================================================
FAIL: test_check_inplace_nn_ReLU_xpu_float64 (__main__.TestModuleXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_modules.py", line 85, in test_wrapper
    return test(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_modules.py", line 208, in test_check_inplace
    self.assertEqual(input_args[0].grad, input_arg_copy[0].grad)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1877, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1e-05 and atol=1e-05, found 60 element(s) (out of 120) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 8.584910560584394 (-0.5233782422802729 vs. 8.06153231830412), which occurred at index (0, 0, 0, 0).

======================================================================
FAIL: test_forward_nn_AvgPool1d_xpu_float32 (__main__.TestModuleXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_modules.py", line 85, in test_wrapper
    return test(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_modules.py", line 45, in test_forward
    self.assertEqual(outputs, ref_outputs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1877, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1e-05 and atol=1e-05, found 9 element(s) (out of 9) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 7.319949567317963 (7.080937385559082 vs. -0.23901218175888062), which occurred at index (2, 2).

======================================================================
FAIL: test_forward_nn_Linear_xpu_float32 (__main__.TestModuleXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_modules.py", line 85, in test_wrapper
    return test(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_modules.py", line 45, in test_forward
    self.assertEqual(outputs, ref_outputs)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1877, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1e-05 and atol=1e-05, found 32 element(s) (out of 32) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 6.04262575507164 (-6.2465972900390625 vs. -0.20397153496742249), which occurred at index (0, 2).

----------------------------------------------------------------------
Ran 52 tests in 12.879s

FAILED (failures=5, skipped=2)
Raised CalledProcessError: return code 1.