test_ctor_with_numpy_scalar_ctor_xpu (__main__.TestNumPyInteropXPU) ... skipped 'Only runs on cpu'
test_from_list_of_ndarray_warning_xpu (__main__.TestNumPyInteropXPU) ... ok
test_from_numpy_xpu (__main__.TestNumPyInteropXPU) ... ok
test_has_storage_numpy_xpu (__main__.TestNumPyInteropXPU) ... ERROR
test_multiplication_numpy_scalar_xpu (__main__.TestNumPyInteropXPU) ... skipped 'Only runs on cpu'
test_numpy_array_interface_xpu (__main__.TestNumPyInteropXPU) ... skipped 'Only runs on cpu'
test_numpy_index_xpu (__main__.TestNumPyInteropXPU) ... skipped 'Only runs on cpu'
test_numpy_non_writeable_xpu (__main__.TestNumPyInteropXPU) ... skipped 'Only runs on cpu'
test_numpy_scalar_cmp_xpu_bfloat16 (__main__.TestNumPyInteropXPU) ... ok
test_numpy_scalar_cmp_xpu_bool (__main__.TestNumPyInteropXPU) ... ok
test_numpy_scalar_cmp_xpu_complex128 (__main__.TestNumPyInteropXPU) ... skipped 'dtype not support on XPU'
test_numpy_scalar_cmp_xpu_complex64 (__main__.TestNumPyInteropXPU) ... skipped 'dtype not support on XPU'
test_numpy_scalar_cmp_xpu_float16 (__main__.TestNumPyInteropXPU) ... ok
test_numpy_scalar_cmp_xpu_float32 (__main__.TestNumPyInteropXPU) ... ok
test_numpy_scalar_cmp_xpu_float64 (__main__.TestNumPyInteropXPU) ... ok
test_numpy_scalar_cmp_xpu_int16 (__main__.TestNumPyInteropXPU) ... ok
test_numpy_scalar_cmp_xpu_int32 (__main__.TestNumPyInteropXPU) ... ok
test_numpy_scalar_cmp_xpu_int64 (__main__.TestNumPyInteropXPU) ... ok
test_numpy_scalar_cmp_xpu_int8 (__main__.TestNumPyInteropXPU) ... ok
test_numpy_scalar_cmp_xpu_uint8 (__main__.TestNumPyInteropXPU) ... ok
test_numpy_unresizable_xpu (__main__.TestNumPyInteropXPU) ... skipped 'Only runs on cpu'
test_parse_numpy_int_xpu (__main__.TestNumPyInteropXPU) ... skipped 'Only runs on cpu'
test_to_numpy_bool_xpu (__main__.TestNumPyInteropXPU) ... ok
test_to_numpy_xpu (__main__.TestNumPyInteropXPU) ... skipped 'Only runs on cpu'

======================================================================
ERROR: test_has_storage_numpy_xpu (__main__.TestNumPyInteropXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 402, in instantiated_test
    raise rte
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_numpy_interop.py", line 396, in test_has_storage_numpy
    self.assertIsNotNone(torch.tensor(arr, device=device, dtype=torch.uint8).storage())
RuntimeError: unsupported Storage type

----------------------------------------------------------------------
Ran 24 tests in 0.489s

FAILED (errors=1, skipped=10)
Raised CalledProcessError: return code 1.